### ISSUE TITLE
Link Other Resource

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/workflows-samples#12]
There are a few developer resource we could link in this repo:

- https://github.com/meteatamel/workflow-samples
- https://github.com/filipknapik/google_workflows
- https://www.youtube.com/watch?v=Uz8G8fTwwXs
- https://atamel.dev/posts/2020/09-08_first_look_at_workflows

Maybe we can make it easier to add community samples, somehow?

https://github.com/GoogleCloudPlatform/community

**Comment by averikitsch** [comment]
These would be difficult to keep up to date.

**Comment by grant** [comment]
> These would be difficult to keep up to date.

Agreed!
