### ISSUE TITLE
Samples for secret manager not working

### ISSUE THREAD

**Issue by Mistic92** [GoogleCloudPlatform/workflows-samples#128]
Samples are not working, I was trying to set params by hand with different variations but all the time I'm getting errors, often TypeError :/ Really documentation for Workflows looks outdated.

**Comment by averikitsch** [comment]
Hi @Mistic92 , can you provide the file you edited and the full error message?

**Comment by averikitsch** [comment]
I have tested both `connectors/connector_secretmanager.workflows.yaml` and `connector_access_secret.workflows.yaml` without issue.
