### ISSUE TITLE
Firestore connector read example isn't working

### ISSUE THREAD

**Issue by dParadiz** [GoogleCloudPlatform/workflows-samples#16]
## Expected Behavior

Working workflow based connector_read_firestore.workflows.yaml example

## Actual Behavior

Workflow execution fails with:

`in step "readFromFirestore": {"message":"TypeError: unsupported operand type for call: 'dict' (expecting callable)","tags":["TypeError"]}`

## Steps to Reproduce the Problem

1. Create new workflow
2. Copy workflow definition from connector_read_firestore.workflows.yaml into workflow
3. Execute workflow

**Comment by joshzhang-google** [comment]
@dParadiz I believe this problem has been fixed. Could you re-deploy your workflow and see if it works?

**Comment by joshzhang-google** [comment]
@dParadiz by the way, please refer to https://github.com/GoogleCloudPlatform/workflows-samples/tree/main/src/connectors for connector samples. Connector calls have retry mechanism built-in so there's no need to wrap the step inside a retry.
