### ISSUE TITLE
update schema to include `parallel` property

### ISSUE THREAD

**Issue by rogerthatdev** [GoogleCloudPlatform/workflows-samples#163]
## Expected Behavior
To better support autocomplete, the [workflows schema](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/workflows.json) requires a definition for the `parallel` property in the `step` definition

Documented usage: https://cloud.google.com/workflows/docs/reference/syntax/parallel-steps

**Comment by muncus** [comment]
Merged!
