### ISSUE TITLE
Sample Request - working with text functions

### ISSUE THREAD

**Issue by jduncan-rva** [GoogleCloudPlatform/workflows-samples#175]
## Expected Behavior

I should be able to find examples of common text operations, such as global replacements or stripping out an undesired character from a file using text.replace, text.replace_all, text.replace_all_regex, etc.

## Actual Behavior

These examples don't exist.

- Version: all
- Platform: all

**Comment by rogerthatdev** [comment]
Thank you for your feedback!

**Comment by camiekim** [comment]
Examples have now been added to the standard library function docs. For example: https://cloud.google.com/workflows/docs/reference/stdlib/text/replace_all
