### ISSUE TITLE
Firestore Connector example describe BigQuery Connector

### ISSUE THREAD

**Issue by hideto0710** [GoogleCloudPlatform/workflows-samples#23]
## Expected Behavior
[connectors/connector_firestore.workflows.yaml](https://github.com/GoogleCloudPlatform/workflows-samples/blob/main/src/connectors/connector_firestore.workflows.yaml) describe Firestore Connector

## Actual Behavior
BigQuery Connector

also https://cloud.google.com/workflows/docs/reference/googleapis/firestore/Overview

**Comment by joshzhang-google** [comment]
Fixed! Thanks for the feedback.
