### ISSUE TITLE
input Json sending the DataType as string always

### ISSUE THREAD

**Issue by lingarajukamble** [GoogleCloudPlatform/workflows-samples#50]
## Expected Behavior
api called inside the workflow should get the datatype of the input parameters as given in json.

input json as below
{
	"candidate_project_key": 1,
	"development_phase": "Phase III",
	"end_date": "",
	"is_archive_only": false,
	"start_date": "",
	"study_description": "TEST_7OCT21_3",
	"study_id": "TEST_11OCT21_3",
	"study_title": "TEST_11OCT21_3",
	"therapeutic_area_key": 78,
	"token": "eyJraWQiOiJsdf1cm9mU1RtNGNwRnFvM3hJVjdVblVZUzVfVXRzcE1JNk1pXzhEY2tPdHFBIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULjNUR1Bic0kxNVFMNFB6NHlIVzdHQTdBZUtCVTUxQXdQTHYsd1bS1jQ3YxOTAiLCJpc3MiOiJodHRwczovL2ludGllbnQtZGV2Lm9rdGFwcmV2aWV3LmNvbS9vYXV0aDIvYXVzcmVxNGJoY1dQdlFna1YwaDciLCJhdWQiOiJpbnRpZW50IiwiaWF0IjoxNjMzOTMzNzU0LCJleHAiOjE2MzM5"
}

## Actual Behavior
here even though the json input is having integer, boolean values the api is being passed with all the values as string.

## Steps to Reproduce the Problem

1. create an dummy api which expects integer, boolean and string values as inputs
1. create an workflow to call the above created api and print the types of the input parameters
1. run the workflow with a json having boolean, string and interger values

Below is the workflow yaml
main:
  params: [run_args]
  steps:
  - step1:
        
        call: http.post
        args:
            url: https://internal_application.com/web/clin/api/dataservices/studies
            headers: 
              content-type: application/json
              authorization: ${"Bearer "+run_args.token}
            body:
                "study_title": run_args.study_title
                "therapeutic_area_key": run_args.therapeutic_area_key
                "development_phase": run_args.development_phase
                "study_description": run_args.study_description
                "study_id": run_args.study_id
                "candidate_project_key": run_args.candidate_project_key
                "start_date": run_args.start_date
                "end_date": run_args.end_date
                "is_archive_only": run_args.is_archive_only
        result: api_response

## Specifications
google cloud workflow
- Version:
- Platform: google cloud platform

**Comment by KrisBraun** [comment]
In JSON, datetimes are simply strings. They are often ISO 8601 format. With the recently released [`time.parse`](https://cloud.google.com/workflows/docs/reference/stdlib/time/parse), these string dates can be converted to Workflows timestamps (Epoch seconds in a float).
