### ISSUE TITLE
sys.now() not functioning

### ISSUE THREAD

**Issue by burnzy** [GoogleCloudPlatform/workflows-samples#7]
Is there a trick to using the `sys.now()` function — I'm having trouble getting that to work properly in my workflows.
I couldn't find any specific documentation around it though.

https://github.com/GoogleCloudPlatform/workflows-samples/blob/5c8a7171c27496e78df670f1fc5e7668960fbd99/src/connector_schedule_tasks.workflows.yaml#L36

**Comment by grant** [comment]
I think this is a super new feature. It might not be enabled for everyone perhaps. Documentation is on the way.

@samodell Do you know?

**Comment by burnzy** [comment]
Ah okay, I thought that might be the case. Thanks @grant

**Comment by grant** [comment]
It should probably be support with gcloud workflows (no beta, gcloud v324.0.0+)

**Comment by grant** [comment]
Workflows recently went generally available.

With that, the documentation was updated. Here's the link to `sys.now()` and other `sys` functions.

https://cloud.google.com/workflows/docs/reference/stdlib/sys/now

😄
