### ISSUE TITLE
Improve Autocompletion Setup Instructions

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/workflows-samples#9]
## Expected Behavior

There should be very clear instructions on how to provide autocompletion for workflow files. And an image/GIF.

<img width="723" alt="Screen Shot 2020-12-05 at 22 20 55" src="https://user-images.githubusercontent.com/744973/101271440-4c2b2100-3748-11eb-9ef6-57c0af12a0a2.png">

**Comment by rogerthatdev** [comment]
I've added this issue as a feature request for future consideration.

**Comment by meteatamel** [comment]
FYI, I blogged about this a while back, in case it's useful: https://medium.com/google-cloud/auto-completion-for-workflows-json-and-yaml-on-visual-studio-code-875a5e878d5e
